config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :categories, except: [:update, :edit, :destroy] do
    resources :payments, only: [:new, :create]
  end

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :category_payments, dependent: :destroy
  has_many :payments, through: :category_payments

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/category_payment.rb
class CategoryPayment < ApplicationRecord
  belongs_to :category
  belongs_to :payment
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :category_payments, dependent: :destroy
  has_many :categories, through: :category_payments

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy, foreign_key: :author_id
  has_many :payments, dependent: :destroy, foreign_key: :author_id

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    categories_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = current_user.categories
  end

  def show
    @category = Category.find(params[:id])
    if @category.author != current_user
      flash[:alert] = 'You can only see what you created'
      redirect_to categories_path
    end
    @payments = @category.payments.order(created_at: :desc)
    @total = @payments.sum(:amount)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.author = current_user
    if @category.save
      flash[:notice] = 'Category was successfully created'
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index; end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @category = Category.find(params[:category_id])

    if @category.author == current_user
      @payment = Payment.new
    else
      flash[:alert] = 'You can only create payments from your categories'
      redirect_to categories_path
    end
  end

  def create
    @category = Category.find(params[:category_id])
    if @category.author != current_user
      flash[:alert] = 'You can only create payments from your categories'
      redirect_to categories_path
    end
    if payment_params[:category_ids].length == 1
      flash[:alert] = 'Must select at least one category'
      redirect_to new_category_payment_path(@category)
    else
      @category = Category.find(params[:category_id])
      @payment = Payment.new(payment_params)
      @payment.author = current_user

      if @payment.save
        flash[:notice] = 'Payment was created successfully'
        redirect_to @category
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  private

  def payment_params
    params.require(:payment).permit(:name, :amount, category_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class="d-flex flex-column justify-content-between align-items-between" style="height: 80vh">
  <h1 class="mb-3">Categories</h1>

  <div>
    <% @categories.each do |category| %>
      <div class="card mb-1">
        <div class="card-body">
          <div class="row">
            <div class="col">
              <%= image_tag(category.icon, alt: "Icon pic", height: "40px") %>
            </div>
            <div class="col-8">
              <%= link_to category.name, category_path(category) %>
            </div>
            <div class="col">
              $<%= category.payments.sum(:amount) %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to "ADD NEW CATEGORY", new_category_path, class: "btn btn bg-lime-400 text-white p-4 text-xl" %>
</div>

app/views/categories/new.html.erb
<div class="d-flex flex-column justify-content-between align-items-between">

  <%= render 'shared/errors', obj: @category %>
  <%= form_with model: @category, class: "d-flex flex-column justify-content-between align-items-between" do |form| %>
    <div class="mb-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :icon, class: "form-label" %>
      <%= form.text_field :icon, class: "form-control", placeholder: "Icon URL" %>
    </div>

    <%= form.submit class: "btn btn-primary" %>

  <% end %>

  <%= link_to "Back", categories_path, class: "btn btn-secondary mt-2" %>
</div>

app/views/categories/show.html.erb
<div class="d-flex flex-column justify-content-between align-items-between" style="height: 80vh">
  <div class="row">
    <div class="col-8">
      <h2><%= @category.name %></h2>
    </div>
    <div class="col-4">
      <p>$<%= @total %></p>
    </div>
  </div>

  <div>
    <% @payments.each do |payment| %>
      <div class="card mb-2">
        <div class="card-body">
          <div class="row">
            <div class="col-10">
              <%= payment.name %>
            </div>
            <div class="col-2">
              $<%= payment.amount %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="d-flex flex-column justify-content-between align-items-between">
    <%= link_to "ADD NEW PAYMENT", new_category_payment_path(@category), class: "btn btn bg-lime-400 text-white p-4 text-xl" %> <br>
    <%= link_to "BACK", categories_path, class: "btn btn-secondary p-4 text-xl" %>
  </div>
</div>

app/views/home/index.html.erb
<div class="flex justify-center">
  <div class="mt-16 px-8 py-4 w-96 bg-white rounded-lg shadow-lg h-fit">
    <h2 class="text-xl font-bold text-center text-gray-700">Welcome toBudget Tracker app</h2>

  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn-warning mb-2" %>
  <% else %>
   <button type="button" class=" w-full bg-blue-500 hover:bg-blue-100 rounded-lg py-2 text-center font-bold cursor-pointer mt-8 text-white">
         <%= link_to "Sign in", new_user_session_path %><br>
      </button>
      <button type="button" class=" w-full bg-blue-700 hover:bg-blue-100 rounded-lg py-2 text-center font-bold cursor-pointer mt-8 text-white">
         <%= link_to "Sign up", new_user_registration_path %>
      </button>
  <% end %>

</div>
</div>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Budget Tracker', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Categories', categories_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to "Logout", destroy_user_session_path,method: :delete, data: { turbo_method: :delete }, :class => 'nav-link' %>
          <% else %>
            <%= link_to "Login", new_user_session_path, :class => 'nav-link' %>
          <% end %>
        </li>
      </ul>
    </div>
    <p class="navbar-text float-right">
      <% if user_signed_in? %>
        <strong><%= current_user.name %></strong>.
      <% end %>
    </p>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "turbo", type: "module" %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
  <div class="container mt-3">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/payments/new.html.erb
<div class="d-flex flex-column justify-content-between align-items-between">
  <%= render 'shared/errors', obj: @payment %>

  <%= form_with model: @payment, url: category_payments_path, class: "d-flex flex-column justify-content-between align-items-between" do |form| %>
    <div class="mb-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :amount, class: "form-label" %>
      <%= form.number_field :amount, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.collection_select(:category_ids, current_user.categories, :id, :name, {}, { multiple: true, size: 7, class: "form-select" }) %>
    </div>

    <%= form.submit class: "btn btn-primary" %>

  <% end %>

  <%= link_to "Back", category_path(@category), class: "btn btn-secondary mt-2" %>
</div>

app/views/shared/_errors.html.erb
<% if obj&.errors&.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>